#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_user:
  path: /index
  controller: App\Controller\UserController::index

app_ajax:
  path: /ajax
  controller: App\Controller\UserController::ajax